gs = require 'gamestate'

require 'lake'

-- resource = {
-- 	kinds = enum:new("img", "aud")
-- }
-- resource.__index = resource
-- function resource:new(name, kind, etc)
-- 	local o = setmetatable(etc, self)
-- 	o.path = name
-- 	o.kind = kind
-- 	o.data = nil
-- 	return o
-- end
-- 
-- function resource:load()
-- 	if     self.kind == self.kinds.img then	self.data = love.graphics.newImage(self.path)
-- 	elseif self.kind == self.kinds.aud then	self.data = love.audio.newSource(self.path, "stream")
-- 	else   print("COULD NOT LOAD RESOURCE OF UNKNOWN KIND "..self.path.."!!!!!!!!") end
-- 	return self.data
-- end
-- 
-- function resource:unload() self.data = nil end
-- 
-- 
-- scene = {}
-- scene.__index = scene
-- function scene:new(path)
-- 	local o = setmetatable({}, self)
-- 	local r = {}
-- 	local base = "scenes/"..path.."/"
-- 	if not love.filesystem.exists(base) then print("BAD PATH :"..base) end
-- 	
-- 	local files = love.filesystem.getDirectoryItems(base)
-- 
-- 	for _, v in ipairs(files) do
-- 		local name = string.split(v, ".")[1]
-- 		local ext = last(string.split(v, "."), -1)
-- 		
-- 		if ext ~= ".json" then
-- 			local kind
-- 			if ext == "png" 					   	   then kind = resource.kinds.img
-- 			elseif table.contains({"wav", "mp3"}, ext) then kind = resource.kinds.aud
-- 			else print("NO KIND FOR RESOURCE "..base..v.."!!!!!") end
-- 		
-- 			local jsonfile = name..".json"
-- 			local jsondata = {}
-- 			if love.filesystem.exists(base..jsonfile) then
-- 				local contents = love.filesystem.read(base..jsonfile)
-- 				jsondata = json.decode(contents)
-- 			end
-- 
-- 			r[name] = resource:new(base..v, kind, jsondata)
-- 		end
-- 	end
-- 
-- 	o.resources = r
-- 	o.guys = {}
-- 	return o
-- end
-- 
-- function scene:load()
-- 	for _, res in pairs(self.resources) do res:load() end
-- 	for _, guy in pairs(self.guys) do guy:loadfrom(self.resources) end
-- end
-- 
-- function scene:addguy(img, tag)
-- 	local res = self.resources[img]
-- 	local ng = guy:new(img, res.ox, res.oy, res.x or 0, res.y or 0)
-- 	if not tag then tag = img end
-- 	
-- 	if not self.guys[tag] then self.guys[tag] = {ng}
-- 	else table.insert(self.guys[tag], ng)
-- 	end
-- end
-- 
-- function scene:guy(img)
-- 	return self.guys[img][1]
-- end
-- 
-- function scene:defguys(t)
-- 	for k, v in pairs(t) do
-- 		self:defguy(k)
-- 		for kk, vv in pairs(v) do self:guy(k)[kk] = vv end
-- 	end
-- end
-- 
-- function scene:deflevel(bg, rects)
-- 	self.bg = self.resources[bg]
-- 	self.rects = rects
-- end
-- 
-- require 'lake'
